# Generated by Django 5.0.3 on 2024-03-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_server_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='public',
            field=models.BooleanField(default=0, null=0),
        ),
    ]
