# Generated by Django 5.0.3 on 2024-03-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_server_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='icon',
        ),
    ]
