# Generated by Django 5.0.3 on 2024-03-10 15:43

import authenticate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to=authenticate.models.server_icon_upload_path),
        ),
    ]
