# Generated by Django 5.0.3 on 2024-03-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="timeline",
            table="timelines",
        ),
    ]
