# Generated by Django 5.0.3 on 2024-04-10 14:00

import django.db.models.deletion
import timeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_timeline_date_modifired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, null=True, upload_to=timeline.models.server_icon_upload_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.timeline')),
            ],
        ),
    ]
